### PR TITLE
feat: use build system to pre-render YAML, add transparent variant

### LINKED ISSUE #3: Does not work with k9s@0.30
After upgrading to k9s@0.30.x the catppuccin/k9s skins no longer seem to work. I can't yet tell if there's a change to the skin schema, but k9s' bundled skins work as expected.

This is what it looks like with `k9s.ui.skin: mocha` configured:
screenshot

### LINKED ISSUE #5: Transparent background variants
Would be great if there were variants for every theme with [terminal background transparency preserved](https://github.com/derailed/k9s/blob/master/skins/transparent.yaml)

### PR DESCRIPTION
**Pull request by nekowinston**
Closes #3 

@mamachanko I'd appreciate if you could give those a look, I compared your pre-rendered, anchor-less files with [dyff](https://github.com/homeport/dyff), there shouldn't be any differences.

### CODE REVIEW

**Comment by mamachanko** [comment]
I may have led you down the wrong path. It turns out that https://github.com/catppuccin/k9s/issues/3 is not related to anchors at all, but k9s expects skins to have `.yaml` as a file extension and **not** `.yml`. The documentation on [k9s#skins](https://k9scli.io/topics/skins/) isn't very forthcoming about this limitation.

In the end it makes sense that anchors aren't the issue because they unmarshal skins with the off-the-shelf go-yaml library: https://github.com/derailed/k9s/blob/982bf6a72873131773862779694520e1ef2dc7e8/internal/config/styles.go#L544

Again, really sorry about the noise @nekowinston !

I think we can close this.

**Comment by nekowinston** [comment]
No worries, I meant to rework the build system for this repo at some point anyways.
So, we need to rename the extensions from `.yml` -> `.yaml` then? I'll just amend this PR.

**Comment by mamachanko** [comment]
> No worries, I meant to rework the build system for this repo at some point anyways. So, we need to rename the extensions from `.yml` -> `.yaml` then? I'll just amend this PR.

Very nice! Ty

**Comment by nekowinston** [comment]
I still can't get Skins to work with 0.30, there are so many conflicting docs for Skin usage out there 😕 

Can you please give me your config with how you got it to work?

I tried `~/.config/k9s/skins/catppuccin-latte.yaml`, `~/.config/k9s/catppuccin-latte_skin.yaml`,
```yaml
k9s:
  ui:
    skin: catppuccin-latte
```
```yaml
k9s:
  skin: catppucin-latte
```

and nothing works

**Comment by mamachanko** [comment]
This is my setup:

```
❯ pwd
/Users/*****/.config/k9s

❯ tree
Ignoring .git and .idea
.
├── aliases.yaml
├── config.yaml
└── skins
    └── catppuccin-mocha.yaml
    
❯ cat config.yaml | yq .k9s.ui.skin
catppuccin-mocha

❯ head skins/catppuccin-mocha.yaml
base: '#1e1e2e'
blue: '#89b4fa'
crust: '#11111b'
flamingo: '#f2cdcd'
green: '#a6e3a1'
lavender: '#b4befe'
mantle: '#181825'
maroon: '#eba0ac'
mauve: '#cba6f7'
overlay0: '#6c7086'    
```

I think that on macOS k9s used (or still uses?) `~/Library/Application\ Support/k9s`. Which means your changes in `~/.config/k9s` might get ignored. I am unsure, but https://github.com/derailed/k9s/issues/1324#issuecomment-1649601099 is a recent comment and mentions a similar issue.

**Comment by mamachanko** [comment]
@nekowinston you did get around the issue eventually?

**Comment by nekowinston** [comment]
Yeah, it turned out that my cluster config was out of date; and since I just wanted to theme it, and not manage my cluster, I assumed it would load the theme first, then try to connect. After fixing that, it loaded the theme without issues. Sorry for the noise.

**Comment by mamachanko** [comment]
No noise at all. Glad to hear it worked out eventually! Thanks for the PR.

**Pull request merged**
